### ISSUE TITLE
IE11 - Object doesn't support property or method 'assign'

### ISSUE THREAD

**Issue by adamwinn** [kartik-v/yii2-dynagrid#214]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-dynagrid.
- [x] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/dynagrid) and [demos](http://demos.krajee.com/dynagrid-demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue
Setup Dynagrid and a DataProvider that allows for sorting.  View the grid in IE11.  

## Expected behavior and actual behavior

When I follow those steps, I see...
Error is shown.
```
jQuery.Deferred exception: Object doesn't support property or method 'assign' TypeError: Object doesn't support property or method 'assign'
   at sortable (https://site/assets/c92e3f8d0be9c026b31dad8166a5aea2/js/html5sortable.js:83:907)
   at KvHtml5Sortable.prototype._init (https://site/assets/c92e3f8d0be9c026b31dad8166a5aea2/js/kv-html5-sortable.js:11:28)
   at KvHtml5Sortable (https://site/assets/c92e3f8d0be9c026b31dad8166a5aea2/js/kv-html5-sortable.js:10:357)
   at Anonymous function (https://site/assets/c92e3f8d0be9c026b31dad8166a5aea2/js/kv-html5-sortable.js:11:442)
   at each (https://site/assets/00b40876bcb31f925b090f433d1ab742/jquery.js:29:158)
   at jQuery.prototype.each (https://site/assets/00b40876bcb31f925b090f433d1ab742/jquery.js:20:178)
   at $.fn.kvHtml5Sortable (https://site/assets/c92e3f8d0be9c026b31dad8166a5aea2/js/kv-html5-sortable.js:11:243)
   at Anonymous function (
```
```
SCRIPT438: Object doesn't support property or method 'assign'
File: jquery.js, Line: 252, Column: 384
```
I was expecting...
No error

#### Browsers

- [ ] Google Chrome
- [ ] Mozilla Firefox
- [x] Internet Explorer
- [ ] Safari

#### Operating System

- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

#### Libraries

- jQuery version: v3.3.1
- yii2-dynagrid version: dev-master 16b9f2b

## Isolating the problem

- [x] This bug happens [on the demos page](https://demos.krajee.com/dynagrid-demo)
**Note: Demo page wouldn't even load in IE11**
- [ ] The bug happens consistently across all tested browsers
**Only IE11**
- [ ] This bug happens when using yii2-dynagrid without other plugins.

**Comment by adamwinn** [comment]
Add the following polyfill and it should work:

https://cdn.polyfill.io/v2/polyfill.js?features=default,Object.entries,Array.prototype.includes

https://github.com/lukasoppermann/html5sortable/issues/445

**Comment by kartik-v** [comment]
Thanks.
